import { execSync } from 'child_process';
import { readFileSync } from 'fs';

const ANTHROPIC_API_KEY = process.env.ANTHROPIC_API_KEY;
const GITHUB_TOKEN = process.env.GITHUB_TOKEN;
const GITHUB_REPO = process.env.GITHUB_REPOSITORY;

async function callClaude(prompt) {
  const response = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'x-api-key': ANTHROPIC_API_KEY,
      'anthropic-version': '2023-06-01',
    },
    body: JSON.stringify({
      model: 'claude-opus-4-6',
      max_tokens: 4096,
      messages: [{ role: 'user', content: prompt }],
    }),
  });
  if (!response.ok) {
    const text = await response.text();
    throw new Error(`Claude API error ${response.status}: ${text}`);
  }
  const data = await response.json();
  return data.content[0].text;
}

async function createGitHubIssue(title, body) {
  const response = await fetch(
    `https://api.github.com/repos/${GITHUB_REPO}/issues`,
    {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${GITHUB_TOKEN}`,
      },
      body: JSON.stringify({ title, body, labels: ['qa-agent', 'bug'] }),
    }
  );
  if (!response.ok) {
    const text = await response.text();
    throw new Error(`GitHub API error ${response.status}: ${text}`);
  }
  return response.json();
}

function run(cmd) {
  try {
    return execSync(cmd, { maxBuffer: 1024 * 1024 * 10 })
      .toString()
      .trim();
  } catch {
    return '';
  }
}

function readFile(path) {
  try {
    return readFileSync(path, 'utf-8');
  } catch {
    return null;
  }
}

async function main() {
  // commits from the last 24 hours
  const recentCommits = run(
    'git log --since="24 hours ago" --oneline --no-merges'
  );
  if (!recentCommits) {
    console.log('No recent commits. Skipping QA.');
    return;
  }

  console.log(`Reviewing commits:\n${recentCommits}\n`);

  // list of changed TS files under src/
  const changedFilesRaw = run('git diff --name-only HEAD~10 HEAD -- "src/"');
  const changedFiles = changedFilesRaw
    .split('\n')
    .filter((f) => f.endsWith('.ts') && !f.endsWith('.test.ts'));

  // diff truncated to 8000 chars
  const diff = run('git diff HEAD~10 HEAD -- "src/"').slice(0, 8000);

  // content of changed route/handler files, up to 8 files, 2000 chars each
  const fileContents = changedFiles
    .filter((f) => f.includes('/api/') || f.includes('/lib/'))
    .slice(0, 8)
    .map((f) => {
      const content = readFile(f);
      if (!content) return '';
      return `### ${f}\n\`\`\`typescript\n${content.slice(0, 2000)}\n\`\`\``;
    })
    .filter(Boolean)
    .join('\n\n');

  const prompt = `You are a senior engineer doing QA on a Next.js API-only backend (TypeScript, Supabase, Viem/Zora blockchain, Arweave).

## Recent commits
${recentCommits}

## Diff of changed files
\`\`\`diff
${diff}
\`\`\`

## Changed file contents
${fileContents}

## Review checklist
Find REAL bugs only — not style issues or theoretical improvements. Focus on:
1. Unhandled Supabase errors (destructured \`error\` ignored or not checked)
2. Missing await / unhandled promise
3. Auth/authorization bypass
4. Silent data loss (catch block swallows error without logging)
5. Regression in existing behavior introduced by the diff

For each bug found output exactly this format:

---
**File:** <path>
**Severity:** critical | high | medium
**Issue:** <one sentence>
**Fix:** <concrete code change>
---

If there are NO real bugs respond with exactly this single line:
NO_BUGS_FOUND`;

  console.log('Sending to Claude Opus 4.6 for review...');
  const result = await callClaude(prompt);
  console.log('\nClaude response:\n', result);

  if (result.trim() === 'NO_BUGS_FOUND') {
    console.log('\nAll clear — no bugs found.');
    return;
  }

  const today = new Date().toISOString().split('T')[0];
  const commitCount = recentCommits.split('\n').length;

  const issueBody = `## QA Agent Report — ${today}

Automated review of the last **${commitCount} commit(s)** found the following issues:

${result}

---
*Generated by nightly QA agent (Claude Opus 4.6)*
*To dismiss false positives, close this issue with label \`qa-noise\`.*`;

  const issue = await createGitHubIssue(
    `[QA Agent] Bugs detected — ${today}`,
    issueBody
  );
  console.log(`\nCreated issue: ${issue.html_url}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
